[project]
name = "huffmanpy"
version = "0.1.0"
description = "Huffman Coding in Python"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "graphviz>=0.20.3",
    "pandas>=2.2.3",
    "rich>=14.0.0",
    "streamlit>=1.45.0",
]
